### ISSUE TITLE
Add ability to capture output as variables

### ISSUE THREAD

**Issue by moritzheiber** [kcmerrill/alfred#27]
I would love to be able to run a task within Alfred and capture the output of said task inside a variable or parameter which I can then pass to another task.

Example pseudo-code:

```yaml
variable:
  summary: Gets a random number
  command: $(($RANDOM%10500+10122))

print.random.number:
  summary: Output of a random number
  command: echo "The number is {{ .variable.Output }}"
```
