### ISSUE TITLE
Registered Variable Example Throwing Error

### ISSUE THREAD

**Issue by bobhenkel** [kcmerrill/alfred#34]
Alfred is awesome, thanks so much!

I'm following along with the example in manual that shows you how to register a reusable value.  When I call alfred forty.two with the below setup I'm getting the error below.

```
fourty.one:
    summary: Register a variable
    register: my.new.var
    command: |
        echo "5678"

fourty.two:
    setup: fourty.one
    summary: Retrieve a registered variable
    command: |
        echo The variable is {{ index .Vars "my.new.var"}}
```

```
[fourty.one] Register a variable (Args: [])
panic: assignment to entry in nil map

goroutine 1 [running]:
panic(0x733c80, 0xc4200fc6d0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/kcmerrill/alfred/alfred.(*Alfred).runTask(0xc4200e1110, 0xc4200fc2d0, 0xa, 0xc420078060, 0x0, 0x0, 0xc420071800, 0x1)
	/go/src/github.com/kcmerrill/alfred/alfred/alfred.go:215 +0x186f
github.com/kcmerrill/alfred/alfred.(*Alfred).runTask(0xc4200e1110, 0x7ffcf7f10e87, 0xa, 0xc420078060, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/kcmerrill/alfred/alfred/alfred.go:143 +0x2b3
github.com/kcmerrill/alfred/alfred.(*Alfred).findTask(0xc4200e1110, 0x68d)
	/go/src/github.com/kcmerrill/alfred/alfred/alfred.go:106 +0x46d
github.com/kcmerrill/alfred/alfred.New(0xc420078060, 0x2, 0x2)
	/go/src/github.com/kcmerrill/alfred/alfred/alfred.go:68 +0x2ba
main.main()
	/go/src/github.com/kcmerrill/alfred/alfred.go:40 +0x1cf
```
