### ISSUE TITLE
Integrating environment variables

### ISSUE THREAD

**Issue by moritzheiber** [kcmerrill/alfred#38]
It would be splendid for Alfred to have a notion of environment variables, and whether they are set or not.

Our code deals with environment variables a lot, and currently it would mean running the following:

```
export.var:
  summary: Export var into Alfred context
  register: my.var
  command: |
      echo "${VAR}"

test.var:
  summary: Tests whether VAR is empty
  test: test -n "{{ index .Vars "my.var" }}"
  fail: set.default.var

set.default.var:
  register: my.var
  command: |
    echo "My default"
```

It's more than a little cumbersome, as you might realize.

Something along these lines would help:

```
my.task:
  env:
    VAR: "My default"
  command: |
    echo "${VAR}"
```

or 

```
my.task:
  env:
    - VAR
  command: |
    echo "${VAR}"
```
and fail if `${VAR}` isn't set.

I could even think you could run other Alfred tasks to fill empty variables:

```
my.var:
  register: my.variable
  command: |
    echo "derp!"

my.task:
  env:
    VAR: {{ index .Vars "my.variable" }}
  command: |
    echo "${VAR}"
```

What do you think?

**Comment by kcmerrill** [comment]
I think Alfred could use a way to interact with env variables for sure. 

Let me chew on this. I'm on holiday but can probably come up with something on the 5th

**Comment by kcmerrill** [comment]
Sorry for the delay. 

So a while back I added `sprig` and it allows the default values for `map[string]interface{}` which means, using your example, you can do this:

```yaml
my.task:
  command: |
    echo "{{ default "derp!" | index .Vars "my.variable" }}"
```
