### ISSUE TITLE
Add support for grok patterns

### ISSUE THREAD

**Issue by iilyak** [kcmerrill/alfred#39]
Alfred is a great tool. Thank you for developing it.

This is not an issue but a feature request
It would be really nice to add automatic parsing of an output of a job and store the parsed groups in the variables.
The idea is inspired by [filebit](https://github.com/elastic/beats/blob/c27aab4128e21eef2759463f849e0870619f1724/filebeat/module/apache2/access/ingest/default.json)

With this feature it would be possible to specify something like (using logstash grok):
```
node.ps:
  summary: Return list of processes on remote node
  register: node.ps
  command: |
    ssh {{ index .Args 0 }} ps -elf
  ok: node.ps.ok
  fail: node.ps.fail
  grok:
    ssh_error: "ssh: (?<ERROR>[^\,]*)"
    process: "%{F} %{S} %{UID}        %{PID}  %{PPID}  %{C} %{PRI}  %{NI} %{ADDR} %{SZ} %{WCHAN  STIME} %{TTY}          %{TIME} %{CMD}"

node.ps.ok:
  register: node.ps.ok
  command:
    echo '{{ index .Vars "node.ps[*][CMD]" }}'  ### <<--- NOT sure about exact syntax here
  private: true

node.ps.fail:
   
   tasks: node.ping
```

There are plenty logstash grok patterns here
https://github.com/logstash-plugins/logstash-patterns-core/blob/master/patterns/

There are few grok engines written in go already.
