### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by kcmerrill** [kcmerrill/alfred#42]
Add checkpoints. That way if the checkpoint exists, you can skip the task. Something like:

```
taskname:
    summary: Some task that gets run
    command: |
        echo "hello world"
   checkpoint: daily|hourly|golangdur(1h|9m|1h9,)
```
