### ISSUE TITLE
Register multiple variables and postprocess output via Masterminds/sprig

### ISSUE THREAD

**Issue by iilyak** [kcmerrill/alfred#51]
I am trying to refactor my draft of a pipeline to use DRY principle. It turns out to be quite hard. How hard it would be to support the following?

```
new:
  summary: Add new item
  command: echo {{ index .Args 0 }}
  register: file_name
  tasks:
    project
    project.edit

project:
  summary: Select project
  command: ls projects | bin/peco --prompt "project>"
  register: 
     project: projects/{{ index .Vars "project" | trim }}
     file_name: projects/{{ index .Vars "project"}}/{{index .Vars "file_name" | trim}}
```
Notice two things:
 - we override old value of `file_name`
 - we use previously registered variable `project` within same task

The `new` task could be improved as well (maybe):
```
new:
  summary: Add new item
  command: none
  register: 
      file_name:  {{ index .Args 0 | trim }}
  tasks:
    project
    project.edit
```

**Comment by kcmerrill** [comment]
Can you give me some more information on what the end goal should be. 

It looks like you're trying to do something based on a list of projects? Not 100% sure, but this might be solved by the [for loop](https://github.com/kcmerrill/alfred/blob/master/TFM.md#for). Perhaps not, either way let me know what youre trying to get out and I"d be happy to take a peek.

**Comment by iilyak** [comment]
I wanted to implement a notes taking feature for GTD workflow. I wanted to write `alfred new <note-file-name>` which would trigger the workflow as follows.
1. ask which project the note should belong to (using https://github.com/peco/peco). The list of available project is list of directories in projects directory. 
2. Construct full path to new file `projects/<project>/<note-file-name>.md`
3. If file does exists alfred should complain and abort
4. If file doesn't exist `project.tepmplate` task would ask for template to use. The list of templates is list of files in `projects/<project>/templates` directory.
5. It copies the template into path constructed in step 2
6. It opens the file using editor

This workflow is working but I have to construct the full path everywhere. I cannot construct it in `project` task. I was thinking to implement internal `strings.trim` task and solve the problem as:
```
project:
   command:  alfred string.trim $(ls projects | bin/peco --prompt "project>")
   register: project

string.trim:
   command: echo {{ index .Args 0 | trim }} 
```

However generic `string` helper wouldn't work because:
1. I need to concatenate `<project>` and `<file_path>`. 

So I would end up with a bunch of private helper tasks.
