### ISSUE TITLE
Is there a replacement for Test command?

### ISSUE THREAD

**Issue by iilyak** [kcmerrill/alfred#53]
New version removes test/fail/ok. Is there any replacement?

**Comment by kcmerrill** [comment]
Fail and Ok should both be there ... if they are not working let me know. 

Regarding test ... that is not a current component. I thought about adding test back in but ultimately every time I've used test, it was better suited to create a new task with ok/fail

**Comment by iilyak** [comment]
I have a following case:
```
ssh.keys:
  summary: Generate ssh keys
  command: bla bla

other.task:
   test: #check if ./ssh.public.key exists
   summary: Do something usefull
   command: bla bla
```

The user would normally use `other.task`. I want it to complain and return error which would inform user that he needs to run `ssh.keys` command once. 
With ok/fail solution ssh.keys would know about `other.task`. 

I'll try to use `checkpoints` or `setup` for this, not sure if it would work.

**Comment by kcmerrill** [comment]
Heh. This is actually the exact use case when I created the `test` component originally. However, over time I found that using `commands` that would fail ultimately was cleaner.

So ... an easy fix for your use case.

```yaml
other.task:
   summary: Do something usefull
   commands: |
      cat ~/.ssh/public.key #or something else useful ... you can use `test`, or `ls` or other things
      bla bla
```
