### ISSUE TITLE
lost part of the readme

### ISSUE THREAD

**Issue by scher200** [kcmerrill/alfred#54]
Hi @kcmerrill what happend to the RTFM, last week it was still complete..

**Comment by kcmerrill** [comment]
I released a new version last night which may/may not have what you're looking for. 

Can you give me an example if what you're looking for, or something that was there that is no longer there

**Comment by scher200** [comment]
Well I was looking how to inherit on task from another, and then apply small adjustments to create a slightly diffrent task from that one.
Last week I was reading something about Alias, but now I could not find it

**Comment by kcmerrill** [comment]
Ahh, yes, aliases. 

I actually got rid of aliases. The biggest reason I didn't bring them back for the latest version was because I typically use https://en.wikipedia.org/wiki/YAML#Advanced_components which allows you to copy/tweak nodes. Essentially creating aliases.

**Comment by scher200** [comment]
Thank you, that is exactly what I was looking for. 
I also missed something about
```
skip: true
```
Great tool you made there, it makes bash more fun!

**Comment by kcmerrill** [comment]
Yeah ... Skip is another one that didn't make the cut. Over the year I used
it, there was only one incredibly specific use case that only popped up
once. In hindsight using ok/fail was the better approach. If you have a
specific use case you could walk me through there is probably an alternative

**Comment by scher200** [comment]
Hi @kcmerrill to get back to inherrit from another task.
The following does not seem to work:
```
notify.ok: &notifySTD
    register:
        resu: "failed"
    command: curl -X POST -d "{{ .Time }} - Result {{ .Vars.resu }} {{ .AllArgs }} {{ .Stdin }}" https://my.local.webhook
    private: true

notify.fail: 
    << *notifySTD
    register:
            resu: "succeded"
```
