### ISSUE TITLE
Failure in setup should prevent the rest of the pipiline from running 

### ISSUE THREAD

**Issue by iilyak** [kcmerrill/alfred#60]
I am testing the `setup` functionality in context of https://github.com/kcmerrill/alfred/issues/53#issuecomment-354180384.
Here is my minimal `alfred.yml` file
```
ensure.ssh.keys:
  summary: Check that ssh keys exist
  command: test -f non_existent_file
  private: true

test:
  summary: Should fail due to setup
  setup: |
    ensure.ssh.keys
  command: >
    echo SUCCESS
```

Here is the output:
```
build/bin/darwin_amd64/alfred test
[    0s] (27 Dec 17 14:10 PST) test started [] Should fail due to setup
[    0s] (27 Dec 17 14:10 PST) test setup ensure.ssh.keys
[    0s] (27 Dec 17 14:10 PST) ensure.ssh.keys started [] Check that ssh keys exist
[    0s] (27 Dec 17 14:10 PST) ensure.ssh.keys command failed
[    0s] (27 Dec 17 14:10 PST) ensure.ssh.keys ✘ failed [] elapsed time '0s'
[    0s] (27 Dec 17 14:10 PST) SUCCESS
[    0s] (27 Dec 17 14:10 PST) test ✔ ok [] elapsed time '0s'
```
