### ISSUE TITLE
chaining tasks

### ISSUE THREAD

**Issue by scher200** [kcmerrill/alfred#61]
Hi @kcmerrill do you also have nice trick to chain tasks
And so that the output of task.one becomes the input of task.two

I could amagine something like:
```
tasks:  task.one | task.two
```

**Comment by kcmerrill** [comment]
I've been thinking about a way to do it. Should be relatively easy and a
feature I've wanted to add for a while. Would you mind sharing your
specific use case?

**Comment by scher200** [comment]
well I am trying to build an alfred module to wrap [openfaas](https://github.com/openfaas/faas).
I like to chain these created functions.
And so that the function one creating an image can be converted to a PNG format by function two.
right now I would need to do this:
```
echo "newimagename" | curl http://localhost:8080/function/random-image-by-name --data-binary @- | curl http://localhost:8080/function/convert-image-png --data-binary @-
```

**Comment by kcmerrill** [comment]
Oh I see. So literally piping via say stdin to another command/task command component?

**Comment by scher200** [comment]
yes, like that:
```
tasks: faas.create.image | faas.convert.image
```

**Comment by kcmerrill** [comment]
I can't quite do that syntax, but this is what I was thinking. Feedback welcome.

https://github.com/kcmerrill/alfred/blob/master/TFM.md#stdin--stringtext-command

**Comment by scher200** [comment]
@kcmerrill this is awesome! 

is there a way I can startoff with a task instead of a command, like 'combine.pipe.one':
```
task.pipe.one:
    stdin: echo "pipe1"
    ok: notify.ok
    fail: notify.fail({{ .TaskName }},{{ .Stdin }})

md5:
    command: |
        md5

combine.pipe.one:
    stdin: task.pipe.one
    ok: md5
    fail: notify.fail({{ .TaskName }},{{ .Stdin }})
```
Ah, yes .TaskName would be an nice one to have for custom type debugging

**Comment by scher200** [comment]
Now I am on fire:
Same thing for register working with tasks:
```
task.one:
    command: echo "this looks really good!"

register:
    summary: Demonstrate the registration of variables
    register:
        taskone: task.one 
        user: whoami
        twitter: "@themayor"
    command: |
      echo "{{ index .Vars "user" }}"
      echo "{{ .Vars.twitter }}"
      echo "{{ .Vars.taskone }}"
```

**Comment by kcmerrill** [comment]
A few things ...

I am going to add a `silent` || `raw` flag to avoid all the output, but keep in mind a valid shell command is `alfred my.task` ;)

So in my next PR you can do something like this: `alfred --no-formatting task.one` and all you get is the raw output without any of the alfred stuff. If you need this right away I'd recommend just sending out put to a log, and then cat'ing out the log in the meantime.

I like the idea of the previous task name being somewhere. Something like `{{ .TaskName }}`

**Comment by scher200** [comment]
Awesome! I look forward to the next PR,
--no-formatting would both boost functionality for my projects.
Please consider to make it possible to log to a variable as well:
```
md5:
    command: |
        md5
    log: Var.Name
```
I am glad you liked the Idea of {{ .TaskName }}
Well it almoast starts to smelling like a programming language :)

**Comment by kcmerrill** [comment]
It's there.

**Comment by scher200** [comment]
You where right, I got what i was looking for:
```
register.pipe:
    summary: Demonstrate pipe of setup registered commands
    register:
        prefix: '{{randAlphaNum 7}}'
        who: '{{ with $prefix := .Vars.prefix | printf "%swho" }}{{ $prefix }}{{ end }}'
        base64encrypt: '{{ with $prefix := .Vars.prefix | printf "%sbase64encrypt" }}{{ $prefix }}{{ end }}'
        base64decrypt: '{{ with $prefix := .Vars.prefix | printf "%sbase64decrypt" }}{{ $prefix }}{{ end }}'
    setup: |
        register.who
        base64.encrypt({{ index .Vars .Vars.who }})
        base64.decrypt({{ index .Vars .Vars.base64encrypt }})
    command: |
        echo "RESULT: {{ index .Vars .Vars.who }} {{ index .Vars .Vars.base64encrypt }} {{ index .Vars .Vars.base64decrypt }}"

register.who:
    register:
        "{{ .Vars.prefix }}who": whoami

base64.encrypt:
    summary: Base64 encryption
    register:
        "{{ .Vars.prefix }}base64encrypt": echo "{{ index .Args 0 }}" | base64

base64.decrypt:
    summary: Base64 decryption
    register:
        "{{ .Vars.prefix }}base64decrypt": echo "{{ index .Args 0 }}" | base64 -d
```
(the whole prefixing is done for if running in multitask mode it would not confict or mix up variable values)

Please let me know if you think this could be done any better.
