### ISSUE TITLE
How to run task in background

### ISSUE THREAD

**Issue by iilyak** [kcmerrill/alfred#85]
I am using alfred to start development environment. My development environment includes few long running processes which need to stay running after `alfred start` finishes. I am sure I am doing something wrong.

I am trying to do something like the following
```
start:
  tasks:
    task1
    task2

task1:
  command: echo task1

task2:
  command: alfred -no-formatting task3 &

task3:
  command: sleep 100 && echo task3
```

**Comment by iilyak** [comment]
following worked 
```
test:
  tasks:
    task1
    task2

task1:
  command: echo task1

task2:
  command: nohup alfred -no-formatting task3 > /dev/null 2>&1 &
  exit: 0

task3:
  command: sleep 100 && echo task3
```
